package ServerOperationApp;


/**
* ServerOperationApp/ServerOperationIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerOperationIDL.idl
* Tuesday, June 12, 2018 10:17:40 PM EDT
*/

public interface ServerOperationIDL extends ServerOperationIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerOperationIDL
