package ServerOperationApp.ServerOperationIDLPackage;


/**
* ServerOperationApp/ServerOperationIDLPackage/stringSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerOperationIDL.idl
* Tuesday, June 12, 2018 10:17:40 PM EDT
*/

public final class stringSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringSeqHolder ()
  {
  }

  public stringSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerOperationApp.ServerOperationIDLPackage.stringSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerOperationApp.ServerOperationIDLPackage.stringSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerOperationApp.ServerOperationIDLPackage.stringSeqHelper.type ();
  }

}
